"""Add game checkpoints for persistence

Revision ID: 1dc78e9cc593
Revises: a06631024034
Create Date: 2025-08-19 17:51:38.449844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc78e9cc593'
down_revision: Union[str, Sequence[str], None] = 'a06631024034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_checkpoints',
    sa.Column('checkpoint_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('game_state', sa.JSON(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['game_rooms.room_id'], ),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index(op.f('ix_game_checkpoints_room_id'), 'game_checkpoints', ['room_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_checkpoints_room_id'), table_name='game_checkpoints')
    op.drop_table('game_checkpoints')
    # ### end Alembic commands ###
