"""Add GameRoom table and update UserSession

Revision ID: 25312fd1d82c
Revises: 51bd7e7c9721
Create Date: 2025-08-16 17:32:29.818437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25312fd1d82c'
down_revision: Union[str, Sequence[str], None] = '51bd7e7c9721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_rooms',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('state', sa.Enum('WAITING', 'IN_GAME', 'FINISHED', name='roomstate'), nullable=False),
    sa.Column('host_session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('game_started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_session_id'], ['user_sessions.user_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_game_rooms_room_code'), 'game_rooms', ['room_code'], unique=True)
    op.add_column('user_sessions', sa.Column('room_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('user_sessions_token_key'), 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['token'], unique=True)
    op.create_foreign_key(None, 'user_sessions', 'game_rooms', ['room_id'], ['room_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.create_unique_constraint(op.f('user_sessions_token_key'), 'user_sessions', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_sessions', 'room_id')
    op.drop_index(op.f('ix_game_rooms_room_code'), table_name='game_rooms')
    op.drop_table('game_rooms')
    # ### end Alembic commands ###
