"""init

Revision ID: ce1ba67c9f3a
Revises: 
Create Date: 2025-08-27 11:45:29.002419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1ba67c9f3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('token', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token'), 'user_sessions', ['token'], unique=True)
    op.create_index('ix_user_sessions_token_active', 'user_sessions', ['token', 'is_active'], unique=False)
    op.create_table('game_rooms',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('room_code', sa.String(length=6), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('phase', sa.Enum('WAITING', 'IN_GAME', 'FINISHED', name='roomphase'), nullable=False),
    sa.Column('host_session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('game_started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_session_id'], ['user_sessions.user_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_game_rooms_room_code'), 'game_rooms', ['room_code'], unique=True)
    op.create_table('game_checkpoints',
    sa.Column('checkpoint_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('game_state', sa.JSON(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['game_rooms.room_id'], ),
    sa.PrimaryKeyConstraint('checkpoint_id')
    )
    op.create_index(op.f('ix_game_checkpoints_room_id'), 'game_checkpoints', ['room_id'], unique=True)
    op.create_table('user_to_room',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['game_rooms.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_sessions.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'room_id', name='uq_user_room')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_room')
    op.drop_index(op.f('ix_game_checkpoints_room_id'), table_name='game_checkpoints')
    op.drop_table('game_checkpoints')
    op.drop_index(op.f('ix_game_rooms_room_code'), table_name='game_rooms')
    op.drop_table('game_rooms')
    op.drop_index('ix_user_sessions_token_active', table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token'), table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
