"""replace circular fks with user_to_room join table

Revision ID: e5fce852c1cb
Revises: 51bd7e7c9721
Create Date: 2025-08-16 18:09:18.575124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fce852c1cb'
down_revision: Union[str, Sequence[str], None] = '51bd7e7c9721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_room',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['game_rooms.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_sessions.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'room_id', name='uq_user_room')
    )
    op.drop_constraint(op.f('user_sessions_room_id_fkey'), 'user_sessions', type_='foreignkey')
    op.drop_column('user_sessions', 'room_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('room_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('user_sessions_room_id_fkey'), 'user_sessions', 'game_rooms', ['room_id'], ['room_id'])
    op.drop_table('user_to_room')
    # ### end Alembic commands ###
